### PR TITLE
Use model to perform queries on QueuedExportAsCsv

### PR DESCRIPTION
**Pull request by gabrieldebem**
## Why?
When we use ORMs different from Eloquent, like Moloquent ou Laravel Sushi, this job doesn't work correctly.
In that case, iinstead of using the query from builder, we can use the method `getModel()` before we do this query to run through the model.

## Pros
- Allow us to use this package in various scenarios with different ORMs

## Cons
- Make this job a little less performant

### CODE REVIEW

**Comment by crynobone** [comment]
Is there a way to determine if `$query->cursor()` is possible instead of forcing all to use `$query->getModel()->cursor()`?

**Comment by gabrieldebem** [comment]
> Is there a way to determine if `$query->cursor()` is possible instead of forcing all to use `$query->getModel()->cursor()`?

yee, we can use this `options` property to validate the query mode.

something like this:

image


```
    private function getQuery()
    {
        return isset($this->options['queryMode']) && $this->options['queryMode'] === 'model'
            ? unserialize($this->query)->getModel()
            : unserialize($this->query);
    }
```


What do you think of this solution?

**Comment by crynobone** [comment]
And how do you determine "queryMode"?

**Comment by crynobone** [comment]
I feel we not covering all scenarios since `$query` should be an instance of `Illuminate\Database\Eloquent\Builder` or `Illuminate\Database\Eloquent\Relations\Relation`, that would be relying on `$query->getModel()` isn't reliable.

**Pull request closed without merging**
